CREATE IF NOT EXISTS TABLE IF NOT EXISTS TLAQUANET_ANALYTICS;
USE DATABASE TLAQUANET_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS PUBLIC;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE(
    ID INTEGER,
    USERNAME STRING,
    DISPLAY_NAME STRING,
    CREATED_AT TIMESTAMP_TZ

);